### ISSUE TITLE
Error when running trimming.smk

### ISSUE THREAD

**Issue by flacchy** [mouliere-lab/ITSFASTR#4]
Hello, I am trying to run the pipeline on the demo dataset before running it on samples to make sure all run properly. 

Once running the first step I incur in this error : 

```bash
(snakemake) -comp020:/ITSFASTR/workflow/rules/1_preprocessing$ snakemake --printshellcmds --keep-going --use-conda  --cores 8 -s trimming.smk
ITSFASTR/workflow/rules/1_preprocessing/trimming.smk:132: SyntaxWarning: invalid escape sequence '\;'
ITSFASTR/workflow/rules/1_preprocessing/trimming.smk:158: SyntaxWarning: invalid escape sequence '\;'
localrules directive specifies rules that are not present in the Snakefile:
	all_trim_Illumina

Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
MissingInputException in rule trim_porechop in file 
ITSFASTR/workflow/rules/1_preprocessing/trimming.smk, line 19:
Missing input files for rule trim_porechop:
    output: /DEMO_ITSFASTR/Test_demo/trimmed/1_trimming/ONT_dummy_sub-100000_32.fastq.gz
    wildcards: porechop_sample=ONT_dummy_sub-100000_32
    affected files:
        /DEMO_ITSFASTR/ITSFASTR_input/ONT_dummy/ONT_dummy_sub-100000_32
```
the samplesheet.csv I have using is the following 
[samplesheet.csv](https://github.com/user-attachments/files/16362504/samplesheet.csv)

and I have followed the instructions to install via conda. Is it possible to have some help? Might be just how I set the sample file 

For the config file as documentation state: _For an ONT run add the path to the folder containing the output folder(s) of base calling or demultiplexing._ I have set the paths to: 

```bash 
# The name of the project will be used to separate the runs.
ProjName: Test_demo
# Path to the sample sheet.
Samplesheet: DEMO_ITSFASTR/samplesheet_demo.csv
# Sequencing type.
# Choose the sequencer [Illumina, ONT]. Deafult is 'Illumina'.
Mode: ONT
# Is this a methylome library? Default is 'False'.
MethLib: False
# Indexed reference path.
# If this is a methylome library please choose a converted index!
RefPath: 
# Path to the directory containing the sample fastqs.
SamplePath: DEMO_ITSFASTR/ITSFASTR_input/ONT_dummy
# Output path.
OutPath: DEMO_ITSFASTR
# Path to TMPDIR.
TmpDir: DEMO_ITSFASTR
# Number of threads to use.
ThreadNr: 8
# The mapping quality of reads to be kept.
FiltQual: 5


```

@moldovannorbert would you be able to help?

**Comment by moldovannorbert** [comment]
Dear @flacchy,

Is it possible that you are not setting the full path to the intput (and for that matter for every other path in the config file)? Depending on what system you are using the path usually contains something like `home/user/`. Can you retry with setting the full path?

**Comment by flacchy** [comment]
Dear @moldovannorbert , 

thanks for this. I just chopped them here as I am using our HPC, all the paths are set as full paths for example "/scratch/hhhh/xxxxx/ffffffffff/DEMO_ITSFASTR/samplesheet.csv" , I am worried I might have not set the sample sheet correctly. I have asked a colleague to re-check the paths just in case . is it expecting the path in the sample sheet ? 

UPDATE: 
I have recreated the sample sheet using the provided script and now it is running 

```bash 
python 3_create_samplesheet.py -d /scratch/xxx/yyy/zzz/DEMO_ITSFASTR/ITSFASTR_input/Dummy_FF/ -o /scratch/xxx/yyy/zzz/DEMO_ITSFASTR/samplesheet_test.csv
```

**Comment by moldovannorbert** [comment]
Dear @flacchy,

I'm happy it works now. Good luck with your research!
